config/settings.dev
for some reason, the DB user got changed to 'adi' instead of 'adicu'
=> edit settings.dev to match DB user adi instead of adicu

density/Documentation.md
=> Added to Documentation Markdown

density/Documentation.md
=> fixed return format langauage and added maclyns notes on using api keys

config/settings.dev, density/db/db.py, density/density.py, density/templates/auth.html, density/tests/test_auth.py
instead of using ```SELECT DISTINCT```, just use the latest dump
=> Building info is slowww

density/templates/docs.html
style sheet needs to be changed to fix font issues see #73
=> first draft of documentation in docs.html

density/static/style.css, density/templates/docs.html
Legible text now. Still a couple minor issues that Jessica will change.
=> Update docs stylesheet.

config/settings.dev, density/db/db.py, density/density.py, density/templates/auth.html, density/tests/test_auth.py
/day routes were returning the first result for the next day, which we do not want.
=> Removed midnight of next day from /day routes

density/templates/docs.html
=> Second draft of documentation

config/requirements.txt, config/settings.dev, density/config/flask_config.py, density/density.py
=> Error handling

density/db/db.py, density/density.py
adds a new field to the json for the /window route. it gives the next URL to use if it exists.
=> added pagination

density/static/style.css, density/templates/auth.html
Should change the height enforcement strategy eventually...
=> Style authentication pages better.

density/density.py, density/templates/layout.html, density/templates/layout_no_header.html
we were getting errors for not setting the offset in the /day routes and when there was no offset parameter specified for the /window routes.
=> fixed layouts and set offset to 0 for default

density/templates/docs.html
:cherries:  i learned how to git cherry-pick :cherries:
=> pull Macyln's docs commit

.travis.yml, density/config/flask_config.py, density/db/db.py, density/density.py, density/tests/test_errors.py
=> Check dates

density/config/flask_config.py, density/db/db.py, density/density.py, density/tests/test_latest.py
- Added percent_full data to all api routes
- Made capacity() simpler by reusing code
- Edited get_latest_data query (in db.py) so that it is ordered alphabetically by group_name
=> Added percent_full data to all api routes.

density/templates/docs.html
=> fixing links in docs page

density/static/style.css, density/templates/auth.html
- it's now a bootstrap button
- match the density page headers background colors
=> customize signin button css

density/static/css/style.css, density/templates/capacity.html
Review @jessvalarezo @evantarrh 
Improve last_updated styling. Fix navbar spacing. Move some CSS around.
I believe this closes #162, but let me know if you encounter the bug
last_updated styling:
The navbar spacing is super subtle so I didn't include a screenshot, but basically there was a space between the navitems and now there isn't.
=> Visual fixes

density/static/js/map.js
The problem was that even though we were checking to make sure the SVG could be resolved to a variable, not all of the elements of the SVG had actually loaded yet. This adds another check before running the JS to make sure that the SVG is 100% loaded.
closes #160 for real this time.
=> fixing bug where map breaks on first load

config/density_dump.sql
Updates to use `Northwest Corner Building`.
The master database is now up to date as well.
closes #114
=> update parent_name in dump

density/density.py, density/tests/test_calculate_capacity.py
The logic in map() and calculate_capacity() was repetitive, so I refactored the code so that calculate_capacity() could be used by both map() and capacity(). I also updated test_calculate_capacity() so it reflects the change.
=> Encapsulate map logic

density/data/capacity_group.json, density/density.py
=> changing back name of noco library to science and engineering

density/templates/about.html
=> added privacy notice

density/static/css/style.css
A little prettier, but not much really. :cake:
=> Make pretty

density/data/__init__.py, density/tests/test_data.py
For each time provided, simply provides the historical
mean of all capacities for the floor over all observations
under the same time and day (ever).
TODO: implement GPR later
modified:   density/data/__init__.py
=> Added very basic prediction function
